# Ansible Playbook to create custom fields in Netbox
# Note: you need to export NETBOX_URL and NETBOX_TOKEN first Example:
# export NETBOX_URL=http://192.168.1.1/
# export NETBOX_token=abcde123456723456!!
---
- name: "NetBox create custom_fields"
  connection: local
  hosts: localhost

  tasks:
    - name: "Task 1: Create a custom for Maintenance Provider"
      netbox.netbox.netbox_custom_field:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          content_types:
            - dcim.device
          name: Maintenance_Provider
          description: "Name of current Maintenance Provider"
          type: text
    - name: "Task 2: Create a custom fields Maintenance Renewal Date"
      netbox.netbox.netbox_custom_field:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          name: Maintenance_Renewal_date
          description: "Current Maintenance Renewal Date"
          type: date
    - name: "Task 3: Create a custom field for the Device Firmware Version"
      netbox.netbox.netbox_custom_field:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          name: Firmware_version
          description: "Current Firmware version running on the device"
          type: text
...
