# Ansible Playbook to pull serial numbers from hosts and add to serial field on the device in Netbox
# Note: you need to export NETBOX_URL and NETBOX_TOKEN first Example:
# export NETBOX_URL=https://192.168.1.1/
# export NETBOX_token=abcde123456723456!!
---
- name: Gather facts from hosts to populate Netbox
  connection: network_cli
  hosts: device_roles_switch
  gather_facts: true

  tasks:
    - name: Assign serial numbers to hosts
      netbox.netbox.netbox_device:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        validate_certs: False
        data:
          name: "{{ item }}"
          serial: "{{ ansible_facts['net_serialnum'] }}"
        state: present
      loop: 
        - "{{ ansible_facts['net_hostname'] }}"
      delegate_to: localhost
...
