---
- name: "Build GH-Labs network in NetBox"
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Iteratively include all task lists"
      include_tasks: "tasks/{{ taskname }}.yml"
      loop:
        - "org"
        - "device"
        - "ipam"
        - "switch_intf"
        - "circuit"
      loop_control:
        loop_var: "taskname"
...
