# Ansible Playbook to add details from a CSV file to custom fields in Netbox
# Note 1: This has not been tested yet but CSV should be structured with hostname,proivder_name & renewal_date as column headers
# Note 2: you need to export NETBOX_URL and NETBOX_TOKEN first Example:
# export NETBOX_URL=https://192.168.1.1/
# export NETBOX_token=abcde123456723456!!
---
- name: Gather facts from hosts to populate Netbox
  connection: network_cli
  hosts: device_roles_switch
  gather_facts: false

  tasks:
    - name: Read users from CSV file and return a dictionary
      community.general.read_csv:
        path: maintenance.csv
        fieldnames: hostname,provider_name,renewal_date
      register: maint
      delegate_to: localhost

    - name: Add Maintenance Provider and renewal dates from CSV file
      netbox.netbox.netbox_device:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        validate_certs: False
        data:
          name: "{{ maint }}"
          custom_fields: 
            Maintenance_Provider: "{{ maint.provider_name }}"
            Maintenance_Renewal_date: "{{ maint.renewal_date }}"
        state: present
      loop: 
        - "{{ maint.hostname }}"
      delegate_to: localhost
...
