---
- name: "Create S{{ swid }} VLAN SVIs"
  netbox.netbox.netbox_device_interface:
    netbox_url: http://localhost:8000/
    netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
    data:
      device: "S{{ swid }}"
      name: "Vlan{{ item.vid }}"  # eg: Vlan10
      type: "virtual"
      enabled: true
      mode: "tagged"
      tagged_vlans:
        - name: "{{ item.name }}"
          site: "{{ location.hq }}"
  loop: "{{ vlan_list }}"
  loop_control:
    label: "Vlan{{ item.vid}} / {{ item.name }}"

- name: "Create IP addresses and assign to S{{ swid }} interfaces"
  netbox.netbox.netbox_ip_address:
    netbox_url: http://localhost:8000/
    netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
    data:
      address: "{{ ip }}"
      status: "active"
      assigned_object:
        device: "S{{ swid }}"
        name: "{{ intf }}"
  vars:
    ip: "{{ item.prefix | ipaddr(swid | string) }}"  # eg: 192.168.10.2/24
    intf: "Vlan{{ item.vid }}"
  loop: "{{ vlan_list }}"
  loop_control:
    label: "{{ intf }} / IP {{ ip }}"

- name: "Update S{{ swid }} primary IP address for future management"
  netbox.netbox.netbox_device:
    netbox_url: http://localhost:8000/
    netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
    data:
      name: "S{{ swid }}"
      primary_ip4: "{{ vlan_list[0].prefix | ipaddr(swid | string) }}"
...
