---
- name: "PLAY 1: SETUP CLUSTER"
  connection: local
  hosts: localhost
  vars:
    vms:
      - { name: gns3, address: 192.168.0.101/24 }
      - { name: awx, address: 192.168.0.102/24 }
      - { name: netbox03, address: 192.168.0.103/24 }
      - { name: prometheus, address: 192.168.0.104/24 }
      - { name: docker01, address: 192.168.0.105/24 }
      - { name: docker02, address: 192.168.0.106/24 }
    pves:
      - { name: pve01, address: "192.168.0.254/24" }
      - { name: pve02, address: "192.168.0.253/24" }
    netbox_headers:
      Content-Type: "application/json"
      Authorization: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
  tasks:
    - name: "TASK 0: CREATE CLUSTER TYPE"
      netbox.netbox.netbox_cluster_type:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: Proxmox
        state: present

    - name: "TASK 1: SYS >> ADD VM CLUSTER"
      netbox.netbox.netbox_cluster:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: GH_Cluster1
          cluster_type: Proxmox
        state: present

    - name: "TASK 2: SYS >> CREATE CLUSTER HOSTS"
      netbox.netbox.netbox_device:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: "{{ item.name }}"
          device_type: CustomServer
          device_role: Server
          site: GH-Lab
      loop: "{{ pves }}"

    - name: "TASK 3: SYS >> SETUP SOME VMs"
      netbox.netbox.netbox_virtual_machine:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: "{{ item.name }}"
          cluster: GH_Cluster1
        state: present
      loop: "{{ vms }}"

    - name: "TASK 4: SYS >> Create interfaces"
      netbox.netbox.netbox_vm_interface:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          virtual_machine: "{{ item.name }}"
          name: eth0
        state: present
      loop: "{{ vms }}"

    - name: "TASK 5: SYS >> ASSIGN IP TO VM"
      uri:
        url: "http://localhost:8000/api/ipam/ip-addresses/"
        method: POST
        headers: "{{ netbox_headers }}"
        status_code: 201
        body_format: json
        body: {
          "address": "{{ item.address }}",
          "status": 1,
          "interface": "{{ item.name | get_interface_id(netbox_headers) }}"
        }
      loop: "{{ vms }}"

    - name: "TASK 6: SYS >> ASSIGN PRIMARY ADDRESS TO THE DEVICE"
      netbox.netbox.netbox_virtual_machine:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: "{{ item.name }}"
          cluster: GH_Cluster1
          primary_ip4: "{{ item.address }}"
        state: present
      loop: "{{ vms }}"
...
