---
- name: "PLAY 1: CLEANUP NETWORK DEVICES"
  connection: local
  hosts: platforms_nxos, platforms_ios, platforms_eos
  tags: [ ios, nxos ]
  tasks:
    - name: "TASK 1: NETBOX >> REMOVE DEVICE TO NETBOX"
      netbox.netbox.netbox_device:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: "{{ inventory_hostname }}"
        state: absent

    - name: "TASK 2: DELETE SW1:2 DEVICE TO NETBOX"
      netbox.netbox.netbox_device:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: "sw-1:2"
          device_type: "IOSv"
          platform: IOS
          serial: "ANSIBLE_FTW"
          rack: GH_01
          status: Active
          device_role: "Switch"
          site: "GH-Lab"
        state: absent
      delegate_to: localhost
      run_once: yes

- name: "PLAY 2: DELETE VM INFO"
  connection: local
  hosts: localhost
  vars:
    vms:
      - { name: gns3, address: 192.168.0.101/24 }
      - { name: awx, address: 192.168.0.102/24 }
      - { name: netbox03, address: 192.168.0.103/24 }
      - { name: prometheus, address: 192.168.0.104/24 }
      - { name: docker01, address: 192.168.0.105/24 }
      - { name: docker02, address: 192.168.0.106/24 }
    pves:
      - { name: pve01, address: "192.168.0.254/24" }
      - { name: pve02, address: "192.168.0.253/24" }
    netbox_headers:
      Content-Type: "application/json"
      Authorization: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
  tasks:
    - name: "TASK 1: SYS >> DELETE SOME VMs"
      netbox.netbox.netbox_virtual_machine:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: "{{ item.name }}"
          cluster: GH_Cluster1
        state: absent
      loop: "{{ vms }}"

    - name: "TASK 2: SYS >> DELETE CLUSTER HOSTS"
      netbox.netbox.netbox_device:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: "{{ item.name }}"
          device_type: CustomServer
          device_role: Server
          site: GH-Lab
        state: absent
      loop: "{{ pves }}"

    - name: "TASK 3: SYS >> DELETE VM CLUSTER"
      netbox.netbox.netbox_cluster:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: GH_Cluster1_Cluster1
          cluster_type: Proxmox
        state: absent

    - name: "TASK 4: DELETE CLUSTER TYPE"
      netbox.netbox.netbox_cluster_type:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: Proxmox
        state: absent

- name: "PLAY 3: CLEANUP BASE NETBOX"
  hosts: localhost
  connection: local
  vars:
    install_state: absent
  tasks:
    - name: "TASK 1: DELETE LOCAL CIRCUIT"
      netbox.netbox.netbox_circuit:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          cid: my-circuit-id
        state: "{{ install_state }}"

    - name: "TASK 2: DELETE CIRCUIT TYPE"
      netbox.netbox.netbox_circuit_type:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: Cable
        state: "{{ install_state }}"
      tags: [ circuit ]

    - name: "TASK 3: DELETE CIRCUIT PROVIDER"
      netbox.netbox.netbox_provider:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: Charter Spectrum
          asn: 7843
          account: AGOODPAYING_ONE
          portal_url: http://spectrum.net
          noc_contact: noc@spectrum.net
          comments: "BEST I CAN GET"
        state: "{{ install_state }}"
      tags: [ circuit ]

    - name: "TASK 4: DELETE PREFIXES"
      netbox.netbox.netbox_prefix:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          family: 4
          prefix: "{{ item.prefix }}"
          site: "GH-Lab"
          status: Active
          description: "{{ item.desc }}"
          is_pool: "{{ item.ispool }}"
        state: "{{ install_state }}"
      loop:
        - { prefix: 10.50.50.0/24, desc: GNS3 Loopbacks, ispool: true }
        - { prefix: 172.31.0.0/24, desc: GNS3 - DC, ispool: false }
        - { prefix: 172.31.1.0/24, desc: GNS3 - DC Mgmt, ispool: false }
        - { prefix: 192.168.0.0/24, desc: GNS3 Remote, ispool: false }
        - { prefix: 192.0.2.0/24, desc: Example Network, ispool: true }
      tags: [ ipam ]

    - name: "TASK 5: DELETE AGGREGRATES"
      netbox.netbox.netbox_aggregate:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          prefix: "{{ item.name }}"
          description: "{{ item.desc }}"
          rir: RFC1918
        state: "{{ install_state }}"
      loop:
        - { name: "10.0.0.0/8", desc: RFC1918 - 10 }
        - { name: "172.16.0.0/12", desc: RFC1918 - 172 }
        - { name: "192.0.2.0/24", desc: RFC5735 - 192.0.2.0 }
        - { name: "192.168.0.0/16", desc: RFC1918 - 192 }
      tags: [ ipam ]

    - name: "TASK 6: DELETE RFC1918 RIR"
      netbox.netbox.netbox_rir:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: RFC1918
          is_private: True
        state: "{{ install_state }}"
      tags: [ ipam ]

    - name: "TASK 7: DELETE VLANS"
      netbox.netbox.netbox_vlan:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: "VLAN{{ item.vid }}"
          vid: "{{ item.vid }}"
          site: "GH-lab"
          description: "{{ item.desc }}"
        state: "{{ install_state }}"
      register: result
      tags: [ ipam ]
      loop:
        - { vid: 100, desc: Demo VLAN }
        - { vid: 200, desc: Primary VLAN }
        - { vid: 300, desc: Secondary VLAN }

    - name: "TASK 8: DELETE DEVICE ROLES"
      netbox.netbox.netbox_device_role:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: "{{ item.name }}"
          color: "{{ item.color }}"
          vm_role: "{{ item.vmrole }}"
        state: "{{ install_state }}"
      loop:
        - { name: Firewall, color: FF0000, vmrole: true }
        - { name: Router, color: 000080, vmrole: true }
        - { name: Switch, color: 008000, vmrole: true }
        - { name: Server, color: "000000", vmrole: false }
        - { name: VM, color: 00FFFF, vmrole: true }
        - { name: Leaf, color: 008000, vmrole: false }
        - { name: Spine, color: 0000FF, vmrole: false }
      tags: [ devices ]

    - name: "TASK 9: DELETE PLATFORMS"
      netbox.netbox.netbox_platform:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: "{{ item.name }}"
          slug: "{{ item.slug }}"
        state: "{{ install_state }}"
      loop:
        - { name: EOS, slug: eos }
        - { name: IOS, slug: ios }
        - { name: IOS-XE, slug: ios-xe }
        - { name: NXOS, slug: nxos }
        - { name: Raspbian, slug: raspbian }
        - { name: Ubuntu 18.04, slug: ubuntu1804 }
        - { name: Ubuntu 16.04, slug: ubuntu1604 }
        - { name: Ubuntu 20.04, slug: ubuntu2004 }
        - { name: Windows 2012, slug: win2012 }
        - { name: Windows 2016, slug: win2016 }
        - { name: Windows 2019, slug: win2019 }
      tags: [ devices ]

    - name: "TASK 10: DELETE DEVICE TYPES"
      netbox.netbox.netbox_device_type:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          model: "{{ item.model }}"
          manufacturer: "{{ item.manufacturer }}"
          slug: "{{ item.slug }}"
          part_number: "{{ item.part_number }}"
          u_height: 1
          is_full_depth: "{{ item.full_depth }}"
        state: "{{ install_state }}"
      loop:
        - {"model": "IOSv", "manufacturer": "Cisco", "slug": "iosv", "part_number": "iosv", "full_depth": False}
        - {"model": "nxosv", "manufacturer": "Cisco", "slug": "nxosv", "part_number": "nxosv", "full_depth": False}
        - {"model": "nx-osv-chassis-nx-osv-supervisor-module", "manufacturer": "Cisco", "slug": "nx-osv-chassis-nx-osv-supervisor-module", "part_number": "nx-osv-chassis-nx-osv-supervisor-module", "full_depth": False}
        - {"model": "CSR1000v", "manufacturer": "Cisco", "slug": "csr1000v", "part_number": "csr1000v", "full_depth": False}
        - {"model": "ASAv", "manufacturer": "Cisco", "slug": "asav", "part_number": "asav", "full_depth": False}
        - {"model": "CustomServer", "manufacturer": "CustomBuild", "slug": "customserver", "part_number": "home", "full_depth": True}
        - {"model": "vEOS", "manufacturer": "Arista", "slug": "veos", "part_number": "veos", "full_depth": False}
      tags: [ devices ]

    - name: "TASK 11: DELETE MANUFACTURERS"
      netbox.netbox.netbox_manufacturer:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: "{{ item }}"
        state: "{{ install_state }}"
      loop:
        - Arista
        - Cisco
        - CustomBuild
        - Raspberry Pi
      tags: [ devices ]

    - name: "TASK 12: DELETE RACKS"
      netbox.netbox.netbox_rack:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: "MN_01"
          site: "GH-lab"
        state: "{{ install_state }}"
      tags: [ sites, devices ]

    - name: "TASK 13: DELETE SITES"
      netbox.netbox.netbox_site:
        netbox_url: http://localhost:8000/
        netbox_token: f5b7a5d5f95f01e111bc954d504a9ac0ba66265c
        data:
          name: "GH-lab"
          time_zone: Europe/London
          status: active
          description: GH lab
          contact_name: Geordie
          contact_email: geordie@gh-lab.com
        state: "{{ install_state }}"
      register: site_setup
      tags: [ sites, devices ]
...
